### ISSUE TITLE
Aluicord isn't opening 

### ISSUE THREAD

**Issue by Alpha2lol** [TymanWasTaken/aliucord-plugins#14]
My aliucord isn't opening when I try opening it, it keeps saying Aliucord isn't responding I took a screenshots.
![Screenshot_20220127-182109](https://user-images.githubusercontent.com/98562626/151459662-e2715310-3c5a-4d66-9995-68d53df5c118.png)

**Comment by TymanWasTaken** [comment]
Not enough information to actually help, if you still need help then go to the aliucord discord https://discord.gg/aliucord
