### ISSUE TITLE
shownames

### ISSUE THREAD

**Issue by Tharki-God** [TymanWasTaken/aliucord-plugins#18]
its not working

**Comment by TymanWasTaken** [comment]
Yes, it doesn't work and I discontinued it because I couldn't make it work

I should probably update the readme

**Comment by Tharki-God** [comment]
well i have made a working plugin for better discord , you  can try looking at that

**Comment by MeFinity** [comment]
> well i have made

wait just a second,you did not

**Comment by Tharki-God** [comment]
> > well i have made
> 
> wait just a second,you did not

i did
