### ISSUE TITLE
The translate plguin just stopped working

### ISSUE THREAD

**Issue by fym35** [TymanWasTaken/aliucord-plugins#3]
![Screenshot_2021-09-04-20-47-53-565_com aliucord](https://user-images.githubusercontent.com/57803365/132105041-74fa47b5-2e1a-4cf7-9f00-5be83433607a.jpg)
![Screenshot_2021-09-04-20-47-50-253_com aliucord](https://user-images.githubusercontent.com/57803365/132105043-656bdd39-3e73-4782-8a22-fba925c49afd.jpg)

**Comment by fym35** [comment]
> @fym35 would you mind trying to translate something and then looking in settings > three dots > debug for any errors?

I dont see any errors there
![Screenshot_2021-09-09-17-40-32-735_com aliucord](https://user-images.githubusercontent.com/57803365/132717901-af65f8ba-cc07-4161-888a-c0a8f320a2cf.jpg)

**Comment by TymanWasTaken** [comment]
This might be fixed in newest version (I can't really test) but if it isn't just tell me on discord Tyman#5998

**Comment by fym35** [comment]
Ok

**Comment by JadeMin** [comment]
i have the same issue and but now ok because the plugin is completely working stopped now by the Aliucord 101.3 update.
