### ISSUE TITLE
[Translate] Untranslate context menu option

### ISSUE THREAD

**Issue by DiamondMiner88** [TymanWasTaken/aliucord-plugins#9]
Please add/replace the translate button on translated messages with untranslate that restores the original message

**Comment by TymanWasTaken** [comment]
I actually thought of adding this a bit ago, but got sidetracked by ReverseImageSearch

I'll add this when I get the chance (shouldn't be too hard)

**Comment by Vendicated** [comment]
do it now

**Comment by TymanWasTaken** [comment]
Totally didn't forget about that until now what are you talking about
